export const getCountryFlag = (country: string): string => {
  const flags: Record<string, string> = {
    "United States": "🇺🇸",
    "USA": "🇺🇸",
    "United Kingdom": "🇬🇧",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "France": "🇫🇷",
    "Japan": "🇯🇵",
    "Italy": "🇮🇹",
    "Spain": "🇪🇸",
    "Germany": "🇩🇪",
    "India": "🇮🇳",
    "Brazil": "🇧🇷",
    "Australia": "🇦🇺",
    "Mexico": "🇲🇽",
    "Israel": "🇮🇱",
    "Morocco": "🇲🇦",
    "Tanzania": "🇹🇿",
    "Thailand": "🇹🇭",
    "Ukraine": "🇺🇦",
    "Netherlands": "🇳🇱",
    "Switzerland": "🇨🇭",
    "Austria": "🇦🇹",
    "Albania": "🇦🇱",
    "Vatican": "🇻🇦",
    "Vatican City": "🇻🇦",
    "Andorra": "🇦🇩",
    "Belgium": "🇧🇪",
    "Croatia": "🇭🇷",
    "Faroe Islands": "🇫🇴",
    "Belarus": "🇧🇾",
    "Bulgaria": "🇧🇬",
    "Åland": "🇦🇽",
    "Bosnia and Herzegovina": "🇧🇦",
    "Cyprus": "🇨🇾",
    "Isle of Man": "🇮🇲",
    "Kosovo": "🇽🇰",
    "Iceland": "🇮🇸",
    "China": "🇨🇳",
    "Monaco": "🇲🇨",
    "Jersey": "🇯🇪",
    "Ireland": "🇮🇪",
    "Montenegro": "🇲🇪",
    "Moldova": "🇲🇩",
    "Luxembourg": "🇱🇺",
    "Liechtenstein": "🇱🇮",
    "Latvia": "🇱🇻",
    "Malta": "🇲🇹",
    "Gibraltar": "🇬🇮",
    "Greece": "🇬🇷",
    "Estonia": "🇪🇪",
    "Lithuania": "🇱🇹",
    "Finland": "🇫🇮",
    "Czechia": "🇨🇿",
    "North Macedonia": "🇲🇰",
    "Hungary": "🇭🇺",
  };
  return flags[country] || "🌍";
};
