project_id = "osmyfzkcydvtwgnbjplx"

[functions.secure-signup]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-help-message]
verify_jwt = false

[functions.send-review]
verify_jwt = false

[functions.send-share-email]
verify_jwt = false

[functions.send-creator-application]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.confirm-template-purchase]
verify_jwt = false
