project_id = "jysvczctvaubgyphcllo"

[functions.secure-signup]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-memorial-invitation]
verify_jwt = false

[functions.create-premium-checkout]
verify_jwt = false
