import { useEffect, useState } from "react";
import { Bell } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { useTranslation } from "react-i18next";

interface Props{memorialId:string;ownerId:string;isOwner:boolean;dateOfDeath:string|null}
const defaults={ninth_day:false,fortieth_day:false,first_anniversary:false,annual_anniversary:false,owner_email_enabled:false};
export function MemorialDateReminders({memorialId,ownerId,isOwner,dateOfDeath}:Props){const {i18n}=useTranslation();const uk=i18n.language==="uk";const {toast}=useToast();const [pref,setPref]=useState<any>(null);const [form,setForm]=useState(defaults);const [recipient,setRecipient]=useState<any>(null);
 useEffect(()=>{if(!dateOfDeath)return;(async()=>{const {data:p}=await supabase.from("memorial_remembrance_preferences").select("*").eq("memorial_id",memorialId).maybeSingle();if(p){setPref(p);setForm(p);const {data:{user}}=await supabase.auth.getUser();if(user&&!isOwner){const {data:r}=await supabase.from("memorial_remembrance_recipients").select("*").eq("preference_id",p.id).eq("recipient_user_id",user.id).maybeSingle();setRecipient(r)}}})()},[memorialId,isOwner,dateOfDeath]);
 if(!dateOfDeath||(!isOwner&&!recipient))return null;const labels:any={ninth_day:uk?"9-й день":"9th day",fortieth_day:uk?"40-й день":"40th day",first_anniversary:uk?"Перша річниця":"First anniversary",annual_anniversary:uk?"Кожна наступна річниця":"Every following anniversary"};
 const save=async()=>{const payload={memorial_id:memorialId,owner_id:ownerId,...form,language:uk?"uk":"en"};const q=pref?supabase.from("memorial_remembrance_preferences").update(payload).eq("id",pref.id):supabase.from("memorial_remembrance_preferences").insert(payload);const {error}=await q;if(error)toast({title:"Error",description:error.message,variant:"destructive"});else{toast({title:uk?"Нагадування збережено":"Reminders saved"});const {data}=await supabase.from("memorial_remembrance_preferences").select("*").eq("memorial_id",memorialId).maybeSingle();setPref(data)}};
 const toggleRecipient=async(v:boolean)=>{if(!recipient)return;const {error}=await supabase.from("memorial_remembrance_recipients").update({opted_in:v,language:uk?"uk":"en"}).eq("id",recipient.id);if(!error)setRecipient({...recipient,opted_in:v})};
 return <section className="my-6 rounded-md border bg-card p-5"><div className="flex gap-3"><Bell className="h-5 w-5 text-primary"/><div className="flex-1"><h3 className="font-serif text-lg font-semibold">{uk?"Дні пам'яті":"Remembrance dates"}</h3>{isOwner?<><p className="mb-4 text-sm text-muted-foreground">{uk?"Усі нагадування вимкнені, доки ви їх не оберете.":"All reminders stay off until you choose them."}</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(labels).map(([k,l])=><label key={k} className="flex items-center gap-2"><Checkbox checked={form[k]} onCheckedChange={v=>setForm({...form,[k]:v===true})}/><span>{l}</span></label>)}</div><label className="mt-4 flex items-center gap-2"><Checkbox checked={form.owner_email_enabled} onCheckedChange={v=>setForm({...form,owner_email_enabled:v===true})}/><span>{uk?"Надсилати мені електронною поштою":"Email me these reminders"}</span></label><Button className="mt-4" onClick={save}>{uk?"Зберегти нагадування":"Save reminders"}</Button></>:<label className="mt-3 flex items-center gap-2"><Checkbox checked={recipient.opted_in} onCheckedChange={v=>toggleRecipient(v===true)}/><span>{uk?"Отримувати обрані родиною нагадування електронною поштою":"Receive the family's remembrance emails"}</span></label>}</div></div></section>}
