import { useEffect, useState } from "react";
import { Bell } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { useTranslation } from "react-i18next";

import { tr } from "@/i18n/tr";
interface Props{memorialId:string;ownerId:string;isOwner:boolean;dateOfDeath:string|null}
const defaults={ninth_day:false,fortieth_day:false,first_anniversary:false,annual_anniversary:false,owner_email_enabled:false};
export function MemorialDateReminders({memorialId,ownerId,isOwner,dateOfDeath}:Props){const {i18n}=useTranslation();const uk=i18n.language==="uk";const {toast}=useToast();const [pref,setPref]=useState<any>(null);const [form,setForm]=useState(defaults);const [recipient,setRecipient]=useState<any>(null);const [family,setFamily]=useState<any[]>([]);const [selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{if(!dateOfDeath)return;(async()=>{const {data:p}=await supabase.from("memorial_remembrance_preferences").select("*").eq("memorial_id",memorialId).maybeSingle();if(p){setPref(p);setForm(p);const {data:{user}}=await supabase.auth.getUser();if(user&&!isOwner){const {data:r}=await supabase.from("memorial_remembrance_recipients").select("*").eq("preference_id",p.id).eq("recipient_user_id",user.id).maybeSingle();setRecipient(r)}if(isOwner){const [{data:access},{data:recipients}]=await Promise.all([supabase.from("memorial_access").select("id,user_id,invited_email,status").eq("memorial_id",memorialId).eq("status","accepted"),supabase.from("memorial_remembrance_recipients").select("access_id").eq("preference_id",p.id)]);setFamily(access??[]);setSelected((recipients??[]).map((r:any)=>r.access_id))}}else if(isOwner){const {data:access}=await supabase.from("memorial_access").select("id,user_id,invited_email,status").eq("memorial_id",memorialId).eq("status","accepted");setFamily(access??[])}})()},[memorialId,isOwner,dateOfDeath]);
 if(!dateOfDeath||(!isOwner&&!recipient))return null;const labels:any={ninth_day:uk?"9-й день":"9th day",fortieth_day:uk?"40-й день":"40th day",first_anniversary:uk?"Перша річниця":"First anniversary",annual_anniversary:uk?"Кожна наступна річниця":"Every following anniversary"};
 const save=async()=>{const payload={memorial_id:memorialId,owner_id:ownerId,...form,language:uk?"uk":"en"};const query=pref?supabase.from("memorial_remembrance_preferences").update(payload).eq("id",pref.id).select().single():supabase.from("memorial_remembrance_preferences").insert(payload).select().single();const {data:saved,error}=await query;if(error){toast({title:tr("a.7f2f6a15cf"),description:error.message,variant:"destructive"});return}setPref(saved);const chosen=family.filter(a=>selected.includes(a.id)&&a.invited_email);if(chosen.length){const rows=chosen.map(a=>({preference_id:saved.id,access_id:a.id,recipient_user_id:a.user_id,recipient_email:a.invited_email,language:uk?"uk":"en"}));await supabase.from("memorial_remembrance_recipients").upsert(rows,{onConflict:"preference_id,recipient_email"})}toast({title:uk?"Нагадування збережено":tr("a.336cfceba7")})};
 const toggleRecipient=async(v:boolean)=>{if(!recipient)return;const {error}=await supabase.from("memorial_remembrance_recipients").update({opted_in:v,language:uk?"uk":"en"}).eq("id",recipient.id);if(!error)setRecipient({...recipient,opted_in:v})};
 return <section className="my-6 rounded-md border bg-card p-5"><div className="flex gap-3"><Bell className="h-5 w-5 text-primary"/><div className="flex-1"><h3 className="font-serif text-lg font-semibold">{uk?"Дні пам'яті":tr("a.926d9b9b02")}</h3>{isOwner?<><p className="mb-4 text-sm text-muted-foreground">{uk?"Усі нагадування вимкнені, доки ви їх не оберете.":tr("a.b9fb276424")}</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(labels).map(([k,l])=><label key={k} className="flex items-center gap-2"><Checkbox checked={Boolean(form[k])} onCheckedChange={v=>setForm({...form,[k]:v===true})}/><span>{String(l)}</span></label>)}</div><label className="mt-4 flex items-center gap-2"><Checkbox checked={form.owner_email_enabled} onCheckedChange={v=>setForm({...form,owner_email_enabled:v===true})}/><span>{uk?"Надсилати мені електронною поштою":tr("a.bbd14ce2ba")}</span></label>{family.length>0&&<div className="mt-4"><p className="mb-2 text-sm font-medium">{uk?"Запросити родину до нагадувань":tr("a.5906b93258")}</p>{family.map(a=><label key={a.id} className="flex items-center gap-2 py-1"><Checkbox checked={selected.includes(a.id)} onCheckedChange={v=>setSelected(v===true?[...selected,a.id]:selected.filter(id=>id!==a.id))}/><span className="text-sm">{a.invited_email}</span></label>)}</div>}<Button className="mt-4" onClick={save}>{uk?"Зберегти нагадування":tr("a.f34ecfdc56")}</Button></>:<label className="mt-3 flex items-center gap-2"><Checkbox checked={recipient.opted_in} onCheckedChange={v=>toggleRecipient(v===true)}/><span>{uk?"Отримувати обрані родиною нагадування електронною поштою":tr("a.20d3a14176")}</span></label>}</div></div></section>}
