// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-memorials.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect this MCP server with your Reflectlife account." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { result: data }
  };
}

// src/lib/mcp/tools/list-memorials.ts
var list_memorials_default = defineTool({
  name: "list_memorials",
  title: "List my memorials",
  description: "List memorial pages created by the signed-in Reflectlife user.",
  inputSchema: {
    limit: z.number().int().describe("Maximum number of memorials to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("memorials").select("id, name, bio, date_of_birth, date_of_death, location, is_public, privacy_level, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/get-memorial.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_memorial_default = defineTool2({
  name: "get_memorial",
  title: "Get memorial details",
  description: "Fetch a single memorial the caller may view, including its recent tributes.",
  inputSchema: {
    memorial_id: z2.string().describe("UUID of the memorial.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ memorial_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: memorial, error } = await supabase.from("memorials").select("id, user_id, name, bio, date_of_birth, date_of_death, location, is_public, privacy_level, created_at").eq("id", memorial_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!memorial) return errorResult("Memorial not found or not visible to you.");
    const { data: tributes } = await supabase.from("memorial_tributes").select("id, tribute_text, created_at").eq("memorial_id", memorial_id).order("created_at", { ascending: false }).limit(10);
    return jsonResult({ memorial, recent_tributes: tributes ?? [] });
  }
});

// src/lib/mcp/tools/create-memorial.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_memorial_default = defineTool3({
  name: "create_memorial",
  title: "Create a memorial",
  description: "Create a new memorial page owned by the signed-in Reflectlife user.",
  inputSchema: {
    name: z3.string().describe("Full name of the person being remembered."),
    bio: z3.string().describe("Short biography or remembrance text.").optional(),
    date_of_birth: z3.string().describe("Date of birth as YYYY-MM-DD.").optional(),
    date_of_death: z3.string().describe("Date of passing as YYYY-MM-DD.").optional(),
    location: z3.string().describe("Place associated with the person.").optional(),
    is_public: z3.boolean().describe("Whether the memorial is publicly visible (default false).").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const name = input.name.trim();
    if (!name) return errorResult("A name is required.");
    const isPublic = input.is_public ?? false;
    const { data, error } = await supabaseForUser(ctx).from("memorials").insert({
      user_id: ctx.getUserId(),
      name,
      bio: input.bio?.slice(0, 5e3) ?? null,
      date_of_birth: input.date_of_birth ?? null,
      date_of_death: input.date_of_death ?? null,
      location: input.location ?? null,
      is_public: isPublic,
      privacy_level: isPublic ? "public" : "private"
    }).select("id, name, is_public, privacy_level, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-diary-entries.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_diary_entries_default = defineTool4({
  name: "list_diary_entries",
  title: "List my diary entries",
  description: "List the signed-in user's private reflection diary entries, newest first.",
  inputSchema: {
    limit: z4.number().int().describe("Maximum number of entries to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("diary_entries").select("id, title, content, entry_date, tags, is_private, created_at").eq("user_id", ctx.getUserId()).order("entry_date", { ascending: false }).limit(max);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/create-diary-entry.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_diary_entry_default = defineTool5({
  name: "create_diary_entry",
  title: "Create a diary entry",
  description: "Write a new reflection diary entry for the signed-in Reflectlife user.",
  inputSchema: {
    title: z5.string().describe("Title of the entry."),
    content: z5.string().describe("Body text of the entry.").optional(),
    entry_date: z5.string().describe("Entry date as YYYY-MM-DD (defaults to today).").optional(),
    tags: z5.array(z5.string()).describe("Optional tags for the entry.").optional(),
    is_private: z5.boolean().describe("Keep the entry private (default true).").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const title = input.title.trim();
    if (!title) return errorResult("A title is required.");
    const { data, error } = await supabaseForUser(ctx).from("diary_entries").insert({
      user_id: ctx.getUserId(),
      title: title.slice(0, 200),
      content: input.content?.slice(0, 2e4) ?? null,
      entry_date: input.entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      tags: input.tags ?? null,
      is_private: input.is_private ?? true
    }).select("id, title, entry_date, is_private, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/add-tribute.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var add_tribute_default = defineTool6({
  name: "add_tribute",
  title: "Leave a tribute",
  description: "Leave a tribute or condolence message on a memorial the caller can access.",
  inputSchema: {
    memorial_id: z6.string().describe("UUID of the memorial."),
    tribute_text: z6.string().describe("The tribute message.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ memorial_id, tribute_text }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const text = tribute_text.trim().slice(0, 2e3);
    if (!text) return errorResult("Tribute text is required.");
    const { data, error } = await supabaseForUser(ctx).from("memorial_tributes").insert({ memorial_id, user_id: ctx.getUserId(), tribute_text: text }).select("id, memorial_id, tribute_text, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "osmyfzkcydvtwgnbjplx";
var mcp_default = defineMcp({
  name: "reflectlife-mcp",
  title: "Reflectlife",
  version: "0.1.0",
  instructions: "Tools for Reflectlife, a memorial and remembrance app. Use these tools to browse and create memorials, leave tributes, and manage the signed-in user's private reflection diary. All access respects the user's own permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_memorials_default, get_memorial_default, create_memorial_default, list_diary_entries_default, create_diary_entry_default, add_tribute_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
