INSERT INTO site_templates (name, country, preview_url, price, is_free, is_creator_template) VALUES
('Andorra - Joaquin Mir Trinxet', 'Andorra', 'https://ik.imagekit.io/zwja8kqgl/Andorra%20Joaquin%20Mir%20Trinxet%20(1).png', 4.99, false, false),
('Belgium - René Magritte', 'Belgium', 'https://ik.imagekit.io/zwja8kqgl/Belgium%20Rene%20Magritte.png', 4.99, false, false),
('Croatia - Vlaho Bukovac', 'Croatia', 'https://ik.imagekit.io/zwja8kqgl/Croatia%20Vlaho%20Bukovac.png', 4.99, false, false),
('Faroe Islands - Flora Heilmann', 'Faroe Islands', 'https://ik.imagekit.io/zwja8kqgl/Far%C3%B6r%20Flora%20Heilmann.png', 4.99, false, false),
('Belarus - Alexander Rodin', 'Belarus', 'https://ik.imagekit.io/zwja8kqgl/Belarus%20Alexander%20Rodin.png', 4.99, false, false),
('Bulgaria - Vladimir Dimitrov', 'Bulgaria', 'https://ik.imagekit.io/zwja8kqgl/Bulgaria%20Vladimir%20Dimitrov.png', 4.99, false, false),
('Åland - Robert Hancock', 'Åland', 'https://ik.imagekit.io/zwja8kqgl/Aland%20Robert%20Hancock.png', 4.99, false, false),
('Bosnia and Herzegovina - Mersad Berber', 'Bosnia and Herzegovina', 'https://ik.imagekit.io/zwja8kqgl/Bosnia%20and%20Herzegovina%20Mersad%20Berber.png', 4.99, false, false),
('Cyprus - Adamantios Diamantēs', 'Cyprus', 'https://ik.imagekit.io/zwja8kqgl/Cyprus%20Adamantios%20Diamant%C4%93s.png', 4.99, false, false),
('Isle of Man - Hilda May Gordon', 'Isle of Man', 'https://ik.imagekit.io/zwja8kqgl/Isle%20of%20men%20Hilda%20May%20Gordon.png', 4.99, false, false),
('Kosovo - Muslim Mulliqi', 'Kosovo', 'https://ik.imagekit.io/zwja8kqgl/KosovoMuslim%20Mulliqi.png', 4.99, false, false),
('Iceland - Nína Tryggvadóttir', 'Iceland', 'https://ik.imagekit.io/zwja8kqgl/Iceland%20N%C3%ADna%20Tryggvad%C3%B3ttir.png', 4.99, false, false),
('China - Gu Kaizhi', 'China', 'https://ik.imagekit.io/zwja8kqgl/China%20Gu%20Kaizhi%20.png', 4.99, false, false),
('Monaco - Emmanuel Bellini', 'Monaco', 'https://ik.imagekit.io/zwja8kqgl/Monaco%20Emmanuel%20Bellini.png', 4.99, false, false),
('Jersey - Sir John Everett Millais', 'Jersey', 'https://ik.imagekit.io/zwja8kqgl/JerseyUKSir%20John%20Everett%20Millais.png', 4.99, false, false),
('Ireland - Jack B. Yeats', 'Ireland', 'https://ik.imagekit.io/zwja8kqgl/Ireland%20Jack%20B.%20Yeats.png', 4.99, false, false),
('Montenegro - Pietro Pocek', 'Montenegro', 'https://ik.imagekit.io/zwja8kqgl/Montenegro%20Pietro%20Pocek.png', 4.99, false, false),
('Moldova - Mihai Grecu', 'Moldova', 'https://ik.imagekit.io/zwja8kqgl/Moldova%20Mihai%20Grecu.png', 4.99, false, false),
('Luxembourg - Joseph Kutter', 'Luxembourg', 'https://ik.imagekit.io/zwja8kqgl/Luxembourg%20Joseph%20Kutter.png', 4.99, false, false),
('Liechtenstein - Johann Michael Bossard', 'Liechtenstein', 'https://ik.imagekit.io/zwja8kqgl/Liechtenstein%20Johann%20Michael%20Bossard.png', 4.99, false, false),
('Latvia - Vilhelms Purvītis', 'Latvia', 'https://ik.imagekit.io/zwja8kqgl/LatviaVilhelms%20Purv%C4%ABtis.png', 4.99, false, false),
('Malta - William Apap', 'Malta', 'https://ik.imagekit.io/zwja8kqgl/Malta%20William%20Apap.png', 4.99, false, false),
('Gibraltar - Gustavo Bacarisas', 'Gibraltar', 'https://ik.imagekit.io/zwja8kqgl/Gibralta%20Gustavo%20Bacarisas.png', 4.99, false, false),
('Greece - El Greco', 'Greece', 'https://ik.imagekit.io/zwja8kqgl/Greece%20El%20Greco.png', 4.99, false, false),
('Estonia - Konrad Mägi', 'Estonia', 'https://ik.imagekit.io/zwja8kqgl/Estonia%20Konrad%20M%C3%A4gi.png', 4.99, false, false),
('Lithuania - Mikalojus Konstantinas Čiurlionis', 'Lithuania', 'https://ik.imagekit.io/zwja8kqgl/Lithuania%20Mikalojus%20Konstantinas%20Ciurlionis.png', 4.99, false, false),
('Finland - Akseli Gallen-Kallela', 'Finland', 'https://ik.imagekit.io/zwja8kqgl/Finland%20Akseli%20Gallen-Kallela.png', 4.99, false, false),
('Czechia - Alphonse Mucha', 'Czechia', 'https://ik.imagekit.io/zwja8kqgl/Czechia%20Alphonse%20Mucha.png', 4.99, false, false),
('North Macedonia - Borislav Traikovski', 'North Macedonia', 'https://ik.imagekit.io/zwja8kqgl/Macedonia%20Borislav%20Traikovski.png', 4.99, false, false),
('Hungary - Philip de László', 'Hungary', 'https://ik.imagekit.io/zwja8kqgl/Hungary%20Philip%20de%20Laszlo.png', 4.99, false, false);