INSERT INTO public.site_templates (name, country, is_free, price, preview_url, description, is_creator_template) VALUES
('Joaquim Mir Trinxet', 'Andorra', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Andorra%20Joaquin%20Mir%20Trinxet%20(1).png', 'Pyrenean landscapes meet impressionist warmth—a tribute reflecting the serene beauty of mountain valleys and enduring memories.', false),
('René Magritte', 'Belgium', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Belgium%20Rene%20Magritte.png', 'Surreal skies and bowler hats frame thoughts beyond the visible—honouring lives that defied the ordinary.', false),
('Vlaho Bukovac', 'Croatia', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Croatia%20Vlaho%20Bukovac.png', 'Adriatic light dances through realist strokes—a coastal embrace preserving sunlit memories forever.', false),
('Vilhelm Hammershøi', 'Denmark', false, 4.99, NULL, 'Quiet Nordic interiors bathed in silver light—a contemplative space for gentle remembrance.', false),
('Akseli Gallen-Kallela', 'Finland', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Finland%20Akseli%20Gallen-Kallela.png', 'Karelian myths and boreal forests come alive—honouring roots through Finland''s national romantic spirit.', false),
('Sámal Joensen-Mikines', 'Faroe Islands', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Far%C3%B6r%20Flora%20Heilmann.png', 'Wind-swept cliffs and Atlantic horizons—an island tribute shaped by resilience and raw beauty.', false),
('El Greco', 'Greece', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Greece%20El%20Greco.png', 'Elongated figures reach heavenward in mystical light—a spiritual tribute echoing Byzantine grandeur.', false),
('Munkácsy Mihály', 'Hungary', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Hungary%20Philip%20de%20Laszlo.png', 'Rich, earthy realism from the Hungarian plains—a warm embrace for stories of strength and heritage.', false),
('Jóhannes Sveinsson Kjarval', 'Iceland', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Iceland%20N%C3%ADna%20Tryggvad%C3%B3ttir.png', 'Volcanic landscapes and ethereal light—an Icelandic ode to nature''s untamed memory.', false),
('Jack Butler Yeats', 'Ireland', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Ireland%20Jack%20B.%20Yeats.png', 'Bold expressionist colour captures Irish spirit—a vivid canvas for tales of heart and homeland.', false),
('Vilhelms Purvītis', 'Latvia', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/LatviaVilhelms%20Purv%C4%ABtis.png', 'Snow-laden Baltic forests in soft pastels—a serene Latvian tribute to quiet endurance.', false),
('Mikalojus Konstantinas Čiurlionis', 'Lithuania', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Lithuania%20Mikalojus%20Konstantinas%20Ciurlionis.png', 'Music and painting merge in symbolic harmony—a Lithuanian dreamscape for poetic remembrance.', false),
('Joseph Kutter', 'Luxembourg', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/Luxembourg%20Joseph%20Kutter.png', 'Expressionist warmth from the heart of Europe—bold colours honouring intimate, heartfelt stories.', false),
('Edvard Munch', 'Norway', false, 4.99, NULL, 'Raw emotion flows through Nordic brushstrokes—a powerful tribute to the depths of human feeling.', false),
('Jan Matejko', 'Poland', false, 4.99, NULL, 'Grand historical canvases of Polish glory—a monumental tribute to legacy and national pride.', false),
('Amadeo de Souza-Cardoso', 'Portugal', false, 4.99, NULL, 'Modernist abstraction kissed by Atlantic light—a Portuguese tribute blending tradition with bold vision.', false),
('Nicolae Grigorescu', 'Romania', false, 4.99, NULL, 'Pastoral landscapes of the Carpathian foothills—a gentle Romanian tribute to rural roots and warmth.', false),
('Ivan Meštrović', 'Serbia', false, 4.99, 'https://ik.imagekit.io/zwja8kqgl/SerbiaMaja%20%C4%90oki%C4%87%20Mihajlovi%C4%87.png', 'Sculptural strength rendered in bold form—a Serbian tribute to resilience carved in memory.', false),
('Ladislav Mednyánszky', 'Slovakia', false, 4.99, NULL, 'Misty landscapes and twilight moods—a Slovak tribute to contemplation and quiet beauty.', false),
('Rihard Jakopič', 'Slovenia', false, 4.99, NULL, 'Alpine impressionism in verdant greens—a Slovenian tribute where mountains cradle cherished memories.', false),
('Anders Zorn', 'Sweden', false, 4.99, NULL, 'Luminous watercolours and Nordic realism—a Swedish tribute celebrating life''s fleeting, golden moments.', false),
('William Turner', 'United Kingdom', false, 4.99, NULL, 'Romantic seascapes ablaze with light—a British tribute to the sublime power of nature and memory.', false),
('Ivan Aivazovsky', 'Ukraine', false, 4.99, NULL, 'Moonlit seas and dramatic skies—a Ukrainian tribute to the boundless beauty of hope and horizon.', false),
('Joaquín Torres-García', 'Uruguay', false, 4.99, NULL, 'Constructivist grids meet South American warmth—a Uruguayan tribute to ordered yet heartfelt remembrance.', false),
('Tom Thomson', 'Canada', false, 4.99, NULL, 'Boreal wilderness in vivid autumn hues—a Canadian tribute to the untamed beauty of the north.', false),
('Hiroshige', 'Japan', false, 4.99, NULL, 'Ukiyo-e serenity in delicate woodblock prints—a Japanese tribute to fleeting beauty and eternal peace.', false),
('Wassily Kandinsky', 'Russia', false, 4.99, NULL, 'Abstract compositions of colour and form—a tribute to the spiritual resonance of inner worlds.', false),
('Georgia O''Keeffe', 'United States', false, 4.99, NULL, 'Desert blooms and vast horizons—an American tribute to the grandeur of nature and quiet strength.', false),
('Frida Kahlo', 'Mexico', false, 4.99, NULL, 'Vivid self-expression rooted in Mexican folk art—a fierce tribute to identity, love, and resilience.', false),
('Sidney Nolan', 'Australia', false, 4.99, NULL, 'Outback legends painted in bold, flat colour—an Australian tribute to myth, land, and belonging.', false);