UPDATE public.site_templates SET preview_url = '/templates/andorra-joaquin-mir-trinxet.png' WHERE name = 'Andorra - Joaquin Mir Trinxet';
UPDATE public.site_templates SET preview_url = '/templates/belgium-rene-magritte.png' WHERE name = 'Belgium - René Magritte';
UPDATE public.site_templates SET preview_url = '/templates/croatia-vlaho-bukovac.png' WHERE name = 'Croatia - Vlaho Bukovac';
UPDATE public.site_templates SET preview_url = '/templates/faroe-islands-flora-heilmann.png' WHERE name = 'Faroe Islands - Flora Heilmann';
UPDATE public.site_templates SET preview_url = '/templates/belarus-alexander-rodin.png' WHERE name = 'Belarus - Alexander Rodin';
UPDATE public.site_templates SET preview_url = '/templates/bulgaria-vladimir-dimitrov.png' WHERE name = 'Bulgaria - Vladimir Dimitrov';
UPDATE public.site_templates SET preview_url = '/templates/aland-robert-hancock.png' WHERE name = 'Åland - Robert Hancock';
UPDATE public.site_templates SET preview_url = '/templates/bosnia-mersad-berber.png' WHERE name = 'Bosnia and Herzegovina - Mersad Berber';
UPDATE public.site_templates SET preview_url = '/templates/cyprus-adamantios-diamantes.png' WHERE name = 'Cyprus - Adamantios Diamantēs';
UPDATE public.site_templates SET preview_url = '/templates/isle-of-man-hilda-may-gordon.png' WHERE name = 'Isle of Man - Hilda May Gordon';
UPDATE public.site_templates SET preview_url = '/templates/kosovo-muslim-mulliqi.png' WHERE name = 'Kosovo - Muslim Mulliqi';
UPDATE public.site_templates SET preview_url = '/templates/iceland-nina-tryggvadottir.png' WHERE name = 'Iceland - Nína Tryggvadóttir';
UPDATE public.site_templates SET preview_url = '/templates/china-gu-kaizhi.png' WHERE name = 'China - Gu Kaizhi';
UPDATE public.site_templates SET preview_url = '/templates/monaco-emmanuel-bellini.png' WHERE name = 'Monaco - Emmanuel Bellini';
UPDATE public.site_templates SET preview_url = '/templates/jersey-sir-john-everett-millais.png' WHERE name = 'Jersey - Sir John Everett Millais';
UPDATE public.site_templates SET preview_url = '/templates/ireland-jack-b-yeats.png' WHERE name = 'Ireland - Jack B. Yeats';
UPDATE public.site_templates SET preview_url = '/templates/montenegro-pietro-pocek.png' WHERE name = 'Montenegro - Pietro Pocek';
UPDATE public.site_templates SET preview_url = '/templates/moldova-mihai-grecu.png' WHERE name = 'Moldova - Mihai Grecu';
UPDATE public.site_templates SET preview_url = '/templates/luxembourg-joseph-kutter.png' WHERE name = 'Luxembourg - Joseph Kutter';
UPDATE public.site_templates SET preview_url = '/templates/liechtenstein-johann-michael-bossard.png' WHERE name = 'Liechtenstein - Johann Michael Bossard';
UPDATE public.site_templates SET preview_url = '/templates/latvia-vilhelms-purvitis.png' WHERE name = 'Latvia - Vilhelms Purvītis';
UPDATE public.site_templates SET preview_url = '/templates/malta-william-apap.png' WHERE name = 'Malta - William Apap';
UPDATE public.site_templates SET preview_url = '/templates/gibraltar-gustavo-bacarisas.png' WHERE name = 'Gibraltar - Gustavo Bacarisas';
UPDATE public.site_templates SET preview_url = '/templates/greece-el-greco.png' WHERE name = 'Greece - El Greco';
UPDATE public.site_templates SET preview_url = '/templates/estonia-konrad-magi.png' WHERE name = 'Estonia - Konrad Mägi';
UPDATE public.site_templates SET preview_url = '/templates/lithuania-mikalojus-ciurlionis.png' WHERE name = 'Lithuania - Mikalojus Konstantinas Čiurlionis';
UPDATE public.site_templates SET preview_url = '/templates/finland-akseli-gallen-kallela.png' WHERE name = 'Finland - Akseli Gallen-Kallela';
UPDATE public.site_templates SET preview_url = '/templates/czechia-alphonse-mucha.png' WHERE name = 'Czechia - Alphonse Mucha';
UPDATE public.site_templates SET preview_url = '/templates/north-macedonia-borislav-traikovski.png' WHERE name = 'North Macedonia - Borislav Traikovski';
UPDATE public.site_templates SET preview_url = '/templates/hungary-philip-de-laszlo.png' WHERE name = 'Hungary - Philip de László';