// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jysvczctvaubgyphcllo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5c3ZjemN0dmF1Ymd5cGhjbGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwODE2MTMsImV4cCI6MjA3NjY1NzYxM30.eWM7gr-wgOR0coC62XoJKjNvUhr1YWCFR2zlf2iL5Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});